version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "03:00"
      timezone: Asia/Makassar
    open-pull-requests-limit: 10
    versioning-strategy: increase-if-necessary
    labels:
      - dependencies
      - frontend
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
    groups:
      frontend-patch-minor:
        patterns:
          - "*"

  - package-ecosystem: composer
    directory: "/backend"
    schedule:
      interval: weekly
      day: monday
      time: "03:30"
      timezone: Asia/Makassar
    open-pull-requests-limit: 10
    versioning-strategy: increase-if-necessary
    labels:
      - dependencies
      - backend
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
    groups:
      backend-patch-minor:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "04:00"
      timezone: Asia/Makassar
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - ci
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
